# Generated by Django 6.0.3 on 2026-03-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagiarism_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Scan'), ('scanned', 'Scanned'), ('error', 'Error'), ('not_implemented', 'Not Implemented')], default='pending', max_length=20),
        ),
    ]
