# Generated by Django 6.0.3 on 2026-03-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagiarism_core', '0002_alter_submission_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='tokenized_sentences',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
