# Generated by Django 6.0.3 on 2026-03-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagiarism_core', '0003_submission_tokenized_sentences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Scan'), ('scanned', 'Scanned'), ('error', 'Error'), ('withdrawn', 'Withdrawn'), ('not_implemented', 'Not Implemented')], default='pending', max_length=20),
        ),
    ]
