# Generated by Django 6.0.3 on 2026-03-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagiarism_core', '0003_submission_tokenized_sentences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='lecturers',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='programs',
        ),
        migrations.AddField(
            model_name='program',
            name='name',
            field=models.CharField(blank=True, help_text='e.g. BSc Computer Science', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='programs', to='plagiarism_core.unit'),
        ),
        migrations.AddField(
            model_name='user',
            name='teaching_units',
            field=models.ManyToManyField(blank=True, related_name='teaching_lecturers', to='plagiarism_core.unit'),
        ),
    ]
