# Generated by Django 6.0.3 on 2026-03-31 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plagiarism_core', '0004_remove_unit_lecturers_remove_unit_programs_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('course', 'name', 'year')},
        ),
    ]
