# Generated by Django 6.0.3 on 2026-03-25 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagiarism_core', '0004_alter_submission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='similarityreport',
            name='matches',
        ),
        migrations.CreateModel(
            name='DocumentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_doc_id', models.CharField(max_length=50)),
                ('source_doc_title', models.CharField(max_length=255)),
                ('similarity', models.FloatField()),
                ('notes', models.CharField(blank=True, default='Document-level and block-level similarity', max_length=255, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_matches', to='plagiarism_core.similarityreport')),
            ],
        ),
        migrations.CreateModel(
            name='MatchBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_text', models.TextField()),
                ('source_text', models.TextField()),
                ('score', models.FloatField()),
                ('document_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_blocks', to='plagiarism_core.documentmatch')),
            ],
        ),
    ]
