# Generated by Django 6.0.3 on 2026-03-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagiarism_core', '0005_remove_similarityreport_matches_documentmatch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchblock',
            name='document_match',
        ),
        migrations.AddField(
            model_name='similarityreport',
            name='matches',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='DocumentMatch',
        ),
        migrations.DeleteModel(
            name='MatchBlock',
        ),
    ]
