# Generated by Django 6.0.3 on 2026-04-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plagiarism_core', '0005_alter_program_unique_together'),
        ('plagiarism_core', '0006_remove_matchblock_document_match_and_more'),
    ]

    operations = [
    ]
